kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: groupby
  name: groupby-webserver
  labels:
    app: groupby-webserver
rules:
- apiGroups: ["", "extensions", "autoscaling", "apps"]
  resources: ["pods", "deployments", "replicasets", "horizontalpodautoscalers", "services", "ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: groupby-webserver
  namespace: groupby
  labels:
    app: groupby-webserver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: groupby-webserver
subjects:
  - kind: ServiceAccount
    name: groupby-webserver
    namespace: groupby