apiVersion: v1
kind: Service
metadata:
  name: groupby-webserver
  labels:
    app: groupby-webserver
spec:
  selector:
    app: groupby-webserver
  type: LoadBalancer
  ports:
    - name: "http"
      port: 80
      protocol: TCP
      targetPort: 80